version: "3.3"

services:
    api:
        image: boulundeasv/deploy-example-api-1:${PROMOTE_BUILD_NUMBER}
        environment:
            EnvironmentName: Production
            ElasticUri: http://elasticsearch:9200
        ports:
            - 62002:80
        depends_on:
            - elasticsearch
    web:
        image: boulundeasv/deploy-example-web-1:${PROMOTE_BUILD_NUMBER}
        environment:
            EnvironmentName: Production
        ports:
            - 62001:80
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
    kibana:
        image: docker.elastic.co/kibana/kibana:7.9.2
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        ports:
            - 62003:5601